// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zonfiqsjzejlovhdnqcp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpvbmZpcXNqemVqbG92aGRucWNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNzY1NzksImV4cCI6MjA2MjY1MjU3OX0.1YF41x8zeJVlyE8f4pXeRruiNpeitRV03CNAJ4q8krg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);